gradle.beforeProject { project ->
  ['com.android.application', 'com.android.library'].each { plugin ->
    project.pluginManager.withPlugin(plugin) {
      def staging = System.getenv('MEMENTO_CMAKE_STAGE')
      if (staging) {
        def directory = project.path == ':app' ? staging : "${staging}/${project.name}"
        project.extensions.getByName('android').externalNativeBuild.cmake.buildStagingDirectory = new File(directory)
      }
    }
  }
}
